name: Action
on:
  schedule:
    - cron: '*/6 * * * *'
  workflow_dispatch: {}
  
jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Run
      run: dotnet run --project   GitHubAction/GitHubAction/GitHubAction.csproj ${{secrets.APITOKEN}}
